services:
  db:
    image: postgres:16
    container_name: filamenty_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: filamenty_backend
    restart: unless-stopped
    # env_file: .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    # ports:
    #   - "${BACKEND_PORT}:5000"
    volumes:
      - images:/images

  frontend:
    # build: ./frontend
    build:
      context: ./frontend
      args:
        BACKEND_PORT: ${BACKEND_PORT}
    container_name: filamenty_frontend
    restart: unless-stopped
    # env_file: .env
    # environment:
    #   BACKEND_PORT: ${BACKEND_PORT}
    #   VITE_BASE_URL: http://localhost:${BACKEND_PORT}/api/v2
    ports:
      - "${FRONTEND_PORT}:3000"

volumes:
  postgres_data:
  images:
