services:
  db:
    image: postgres:18
    container_name: filamenty_rs_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql

  backend:
    build: ./backend
    container_name: filamenty_rs_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      HOSTNAME: http://${HOST}
      BACKEND_PORT: ${BACKEND_PORT}
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - backend_images:/app/images

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BASE_URL: http://${HOST}:${BACKEND_PORT}/api/v2
    container_name: filamenty_rs_frontend
    restart: unless-stopped
    environment:
      VITE_BASE_URL: http://${HOST}:${BACKEND_PORT}/api/v2
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  backend_images:
