services:
  db:
    image: postgres:18
    container_name: filamenty_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: filamenty
      POSTGRES_PASSWORD: filamenty
      POSTGRES_DB: filamenty
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: filamenty_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://filamenty:filamenty@db:5432/filamenty
      HOSTNAME: http://www.example.com
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - backend_images:/app/images

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BASE_URL: http://localhost:5000/api/v2
    container_name: filamenty_frontend
    restart: unless-stopped
    environment:
      VITE_BASE_URL: http://localhost:5000/api/v2
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  backend_images:
